### ISSUE TITLE
Projektin dokumentti ja kysymys

### ISSUE THREAD

**Issue by Plankkan** [OtsoBjorklund/maci#6]
Anteeksi tämä viive, mutta nyt olen katsonut läpi projektin dokumentti ja koodit.
Aloitan vaikka dokumentista ensin.

Jos en olisi tiennyt mitään tästä projektista, niin nyt ainakin tietäisin jos lukisin dokumentin läpi. Dokumentti antaa myös vastauksen kaikkiin esimerkki kysymyksiin (https://assamite.github.io/cc-mas-course/project.html#documentation).

Ehdotuksia dokumenttiin:
1. Ajattelin vain että pitäisikö myös jossain mainita että me päämääräisesti käytetään 4 agentteja (1 agentti on liian vähän, ja 100 agentteja on vähäsen liian paljon), ja on helppoa lisätä/poistaa agentteja ihan miten käyttäjä haluaa? Koodissa tämän näkee todella hyvin, ajattelin vain että pitäisikö tämä tieto myös olla dokumentaatiossa.
2. Pitäisikö olla yksi esimerkki output mukana dokumentissa?
3. Ainahan voisi tehdä kuvan miten koko systeemi toimii kronologisesti, kuten esim. (https://github.com/Cabrill/CCMAS16/wiki). Mutta luulen että tämä ei ole tällä hetkellä tarpeellista kun dokumentin teksti kertoo aika hyvin tämän prosessin.
En keksi mitään muuta.

Yksi kysymys koodista (voi olla että tulee lisää vielä):
Katsooko agentti vain kerran, siis alussa, mainittuun MusicXML fileen. Tämän jälkeen se saa motiivi sanaston ja muistaa ne. Tyhmä kysymys, mutta halusin vain varmistaa tämän.

**Comment by KariKorpinen** [comment]
dokumentointi vaikuttaa ok.

Muutamia havaintoja/kysymyksiä koodista

motif.py

def get_string_representation(self):

prev_dur = self.notes[i].duration.quarterLength
- prev_dur muuttuja tarkoittaa nuotti i:n neljännesosan pituutta

def transpose_random_note(motif):
# Limit transposition to a perfect fifth up or down
                transposition = random.randint(-7, 7)
- mikä on rajoituksen tarkoitus/ miksi valittu kvintti

environment.py

def get_latest_motifs(self, age):
    distance = ceil(self.max_agent_memory_capacity / len(self.get_agents(address=False)))

- mitä ceil- funktio tekee?

musicxmlio.py

def select_random_motifs(filename, motif_length, num_motifs):
    while cumulated_duration < motif_length:

-toi oli mielenkiintoinen, luulin, että se ottaa täydet nuotit sisään, mutta se typistää hännästä.

**Comment by KariKorpinen** [comment]
fontti piti olla samaa kokoa koko ajan

**Comment by OtsoBjorklund** [comment]
Agenttien määrä voi olla ihan mitä tahansa, niin en siksi laittanut siitä mitään dokumentaatioon. 

Kvintti valittu sen takia, että transponoinnit pysyisivät joissain rajoissa.
ceil: ceiling funktio, pyöristää ylöspäin. Löytyy varmaan jokaisen ohjelmointikielen matikkakirjastosta.

**Comment by OtsoBjorklund** [comment]
https://www.dropbox.com/s/204myry2jaza52i/Demoslides.odp?dl=0

**Comment by OtsoBjorklund** [comment]
[Demoslides.odp.zip](https://github.com/OtsoBjorklund/maci/files/651181/Demoslides.odp.zip)
